### ISSUE TITLE
Suggestions for general improvement

### ISSUE THREAD

**Issue by SOUMEE2000** [agnivg/temporary-chat-app#1]
1. If any of the fields is blank the app need not direct the user to the room. One can just put a template above the boxes saying that the field is required and can not proceed further without it.
2. The frontend(perhaps the participants list) can be further enhanced in design.
3. As soon as one user leaves the chatroom it appears his details are deleted from the database. So if he rejoins using the same credentials the message given by the admin is that a new user has joined. Maybe their credentials(not the chats) needn't be deleted from the database untill the whole room is dissolved. 

ps. A great chap app overall. It serves as my inspiration to make one myself.

**Comment by agnivg** [comment]
Thank you for your Suggestions.
Regarding (1), I thank you for pointing it out, now I have corrected it.
Regarding (3), My chat app is designed in such a way that when one user leaves the room, all the chats(including messages from him/her and other users) gets deleted for him and not for others. Other users can still see his/her chat. It is a temporary chat app, so in order to reduce data load on the database I am deleting all the chats for him and not for others. When any user leaves the room, chats get deleted for him only and not for others. So when all users leave the room the database becomes empty.
If any user does not want chats to get deleted for him, he should not leave the chat room. This app is different from existing messenger apps.

**Comment by SOUMEE2000** [comment]
Yes I get the fact that this is a temporary chat room. Regarding my point number 3, I had misinterpreted the intentions of the app. My apologies. But its a great app overall.
